name: docker-build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '00 4 * * 3'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Free disk space
      run: sudo rm -rf "/usr/local/share/boost" && sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: Build
      run: ./build_docker.sh

    - name: Run
      run: docker run --rm --volume=$(pwd):/hrnet:rw evroon/hrnet:latest echo 'test'
